#!/usr/bin/env bash
#/* vim: set filetype=sh : */ 

version() { cat <<-EOF
	TIM = literate programming + test suites + code library management. Version 1.0
	Copyright 2009, Tim Menzies, GPL v3.0
EOF
}
copyleft() { version; echo ""; cat<<-EOF
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
EOF
}
credits() { cat<<-EOF
	Credits:
	  - Tim Menzies did most of the coding.
	  - This code uses Jesus Galan's version of Markdown (with a few modifications).
	EOF
}
usage() { 
	echo usage: tim [-[cCmMrRsSo] file] [-[altw] dir] [-T string] [-[DKihvx]]
}
help() { version;  echo ""; cat<<'EOF'
    -a dir        Output directory for exectutable awk files.
    -c file       Write, to standard output,  a 'tim' file 
                  converted to executable awk.
    -C file       Write, to the awk output directory,  a 'tim' file 
                  converted to executable awk.
    -D            Dump some debug information.
    -h            Help.
    -K            Print copyright information.
    -i 			  If generating html, add in a table of contents.
    -l dir        Directory for log files.
    -m file       Write, to standard output,  a 'tim' file 
                  converted to html.
    -M file       Write, to the awk output directory,  a 'tim' file 
                  converted to html.
    -o file       Load the options in the config 'file'. For a list of current
                  options, and their current defaults, type 'tim -D'.
    -r file       Write, to standard output,  the files referenced by 'file'.
    -R file       Sames as -r, but add ' -f ' before each name.
    -s file       If generating an html file, include in-line the CSS 
                  styles in 'file'.
    -S file       If generating an html file, include a link to a CSS styles 
                  in 'file' as an in-line header.
    -t dir        Directory for the 'tim' source files.
    -T string     If generating an html file, use 'string' as the title.
    -v 			  Print version info.
    -w dir        Output directory for html files.
    -x            When generating execitable awks, expand all source code, in-line.
EOF
}
options() { cat<<EOF
# TIM config options.
# Options set in $HOME/.timrc override TIM's default options.
# Also, options set from the TIM command line override $HOME/.timrc

# Directories:
      TimSrc="$TimSrc"      # Directory to store the tim files. Also set by -t.
      TimWeb="$TimWeb"      # Directory to store the web files. Also set by -w.
      TimLog="$TimLog"      # Directory to store the log files. Also set by -l.
     TimCode="$TimCode"     # Directory to store the awk files. Also set by -a.
      TimTmp="$TimTmp"      # Directory for temporaties."

# Programs:
        # Path to awk interpreter. 
        Awk="$Awk"         
        # Path to profiling version of awk interpreter.
        Pawk="$Pawk"        

# Options:
      TimToc="$TimToc"      # If set, when generating HTML, add in a table of contents. Also set by -i.
      TimCSS="$TimCSS"      # Style sheet URL. Also set by -S.
    TimXpand="$TimXpand"    # If set, include nested source. Also set by -x.
    TimTitle="$TimTitle"    # Title for html pages. Also set by -T.
TimInLineCSS="$TimInLineCSS" # In-line style sheet file. Also set by -s.
EOF
}
config() {
	Awk=${Awk:-`which gawk`}
	TimTmp=${TimTmp:-/tmp/$USER/tim}
	Pawk=${Pawk:-"`which pgawk` --dump-variables=$TimTmp/awkvars.out  --profile=$TimTmp/awkprof.out"}
	TimSrc=${TimSrc:-$HOME/opt/tim/src}
	TimWeb=${TimWeb:-$HOME/opt/tim/html}
	TimLog=${TimLog:-$HOME/opt/tim/log}
	TimCode=${TimCode:-$HOME/opt/tim/awk}
	[ -f "$HOME/.timrc" ] && . $HOME/.timrc # optionally, override defaults
	dir! $TimTmp
}
#### startup
opt() {
	case $1 in
	    # pairs of flags
		c) file? $2; cat $2 | c;;
		C) file? $2; cat $2 | c > $TimCode/$Stem.sh;;
		m) file? $2; cat $2 | m ;;
		M) file? $2; cat $2 | m > $TimWeb/$Stem.html;;
		r) file? $2; includes $File;;
		R) file? $2; includes $File | sed 's/ / -f /g';;

		# settings of options
		a) dir!  $2; TimCode=$2;;
	    i) TimToc="1";;
		l) dir!  $2; TimLog=$2;;
		o) file? $2; . $2;;
		s) file? $2; TimInLineCSS=$2;;
		t) dir?  $2; TimSrc=$2;;
		w) dir!  $2; TimWeb=$2;;
		S) TimCSS=$2;;
		T) TimTitle="$2";;
		x) TimXpand="1";;
		
		# other
	    v) version; echo ""; credits;;
	    D) options;;
	    K) copyleft;;
		h) help;;
		*) usage;;
  	esac
}
#### utils
dir!()  { Dir=$1; [ ! -d "$1" ] && mkdir -p $1; }
dir?()  { Dir=$1; [ ! -d "$1" ] && (echo "$1 is not a file."; exit 2);  }
file?() { 
	if [ -f "$1" ] 
	then 
		File=$1
		Stem=`basename $1`
		Stem=${Stem%.*}
	else echo "$1 is not a file."
		 exit 1
	fi
}
#### workers
c() {
	dir! $TimCode
	echo "#!`which gawk` -f "
	local uses=`includes $File`
	arguments $File > $TimCode/${Stem}__args.awk
	if 	[ -n "$TimXpand" ]
	then 
		(date ; copyleft) | sed 's/^/# /'
		for file in $uses
	    do	printf  "\n---| $file |--------------------------\n"
			cat $TimSrc/$file
		done
	fi
	gawk '/^[ \t]*$/   { dump(); next; }
                       { text = (text ? text "\n" : "" ) $0 }
          END          { dump() }
          function dump() {
             if (text) {
                 if (text ~ /^[ \t][^ \t]/)
                         print text "\n"
                 else  {
                        gsub(/\n/,"\n#",text)
                        print "#" text "\n" } }
             text = "";
         }' -
	dir! $TimLog
	echo $uses > $TimLog/$Stem.f
}
includes() {
	gawk '{ ruses($0) } 
          function ruses(line,    name,file,x,a) {
   		     if (  line ~ /@uses/ ) { 
   		     	split(line,a)
			 	name=a[2]
				gsub(/\"/,"",name)
				file = Base "/" name
     			while ((getline x < file) > 0) 
					ruses(x);
				printf(" %s", name) 
     			close(file) }
		  } ' Base=${TimSrc} $1
	echo " $Stem.awk"
}
arguments() {
	cat $File  |
	gawk 'BEGIN {RS=""; FS="\n"}
		 /^Arguments/ {In=1; next}
          In           {gsub(/[\+\*\"]/," ")
						gsub(/\n/,"\\n\"\n\t\"")
						gsub(/\n/,"\\\n")
					    print "function " Stem "__args() { "
					    print "   return \"" $0 "\"\n}" 
				        exit
                       }' Stem=$Stem
}
m() {
	if [ -n "$TimCSS" -o -n "$TimInLineCSS" ]
	then
		echo "<html><header><title>$TimTitle</title>"
		if [ -n "$TimCSS" ]
		then 
           echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"$TimCSS\"/>"
		fi
		if [ -n "$TimInLineCSS" ]
		then echo "<style type=\"text/css\" media=\"all\">"
		   cat $TimInLineCSS 
		   echo "</style>"
		fi
		echo "</header><body>"
		cat - | body
		echo "</body></html>"
	else
		cat - | body
	fi
}
body() {
	if [ -n "$TimTitle" ]; then
		echo "<div class=\"awktop\"><h1><join>$TimTitle</join></h1></div>"
	fi
	if [ -n "$TimToc" ]; then
		echo "<div class=\"awktoc\"><h2>Contents</h2>"	
	    [ -f "$TimLog/$Stem.toc" ] && cat "$TimLog/$Stem.toc"
		echo "</div><div class=\"awkbody\">"
	fi
	cat - | markdown
	[ -n "$TimToc" ] && echo "</div>"
}
markdown() { 
  echo "" > $TimLog/$Stem.toc
  cat - | sed '/^@uses/d' | gawk '
	BEGIN {
		env = "none";
		text = "";
	}
	/^!\[.+\] *\(.+\)/ {
		split($0, a, /\] *\(/);
		split(a[1], b, /\[/);
		imgtext = b[2];
		split(a[2], b, /\)/);
		imgaddr = b[1];
		print "<p><img src=\"" imgaddr "\" alt=\"" imgtext "\" title=\"\" /></p>\n";
		text = "";
		next;
	}
	/\] *\(/ {
		do {
			na = split($0, a, /\] *\(/);
			split(a[1], b, "[");
			linktext = b[2];
			nc = split(a[2], c, ")");
			linkaddr = c[1];
			text = text b[1] "<a href=\"" linkaddr "\">" linktext "</a>" c[2];
			for(i = 3; i <= nc; i++)
				text = text ")" c[i];
			for(i = 3; i <= na; i++)
				text = text "](" a[i];
			$0 = text;;
			text = "";
		}
		while (na > 2);
	}
	/`/ {
		while (match($0, /`/) != 0) {
			if (env == "tt") {
				sub(/`/, "</tt>");
				env = pcenv;
			}
			else {
				sub(/`/, "<tt>");
				pcenv = env;
				env = "tt";
	}   }   }
	/\*\*/ {
		while (match($0, /\*\*/) != 0) {
			if (env == "emph") {
				sub(//, "</emph>");
				env = peenv;
			}
			else {
				sub(/\*\*/, "<emph>");
				peenv = env;
				env = "emph";
	}   }   }
	/^=+[ \t]*$/ {
		Headers++
		print "<a name=\""Headers"\"><h1>" text "</h1></a>\n";
		print "<h1><a href=\"#"Headers"\">" text "</a></h1>" >>Toc
		text = "";
		next;
	}
	/^-+[ \t]*$/ {
		Headers++
		print "<a name=\""Headers"\"><h2>" text "</h2></a>\n";
		print "<h2><a href=\"#"Headers"\">" text "</a></h2>" >>Toc
		text = "";
		next;
	}
	/^_+[ \t]*$/ {
		Headers++
		print "<a name=\""Headers"\"><h3>" text "</h3></a>\n";
		print "<h3><a href=\"#"Headers"\">" text "</a></h3>" >>Toc
		text = "";
		next;
	}	
    /^\.+[ \t]*$/ {
		Headers++
		print "<a name=\""Headers"\"><h4>" text "</h4></a>\n";
		print "<h4><a href=\"#"Headers"\">" text "</a></h4>" >>Toc
		text = "";
		next;
	}
	/^#/ {
		match($0, /#+/);
		n = RLENGTH;
		if(n > 6)
			n = 6;
		print "<h" n ">" substr($0, RLENGTH + 1) "</h" n ">\n";
		next;
	}
	/^[ \t]*[+].*:/ {
		if (env == "none") {
			env = "dl";
			print "<dl>";
		}
		if (text) print text "</dd>"
		sub(/^[ \t]*[+]/,"");
		sub(/:/,"</dt><dd>");
		print "<dt>" $0  ;
		text = "";
		next;
	}
	/^[ \t]*[+]/ {
		if (env == "none") {
			env = "ul";
			print "<ul>";
		}
		if (text) print text 
		sub(/^[ \t]*[+]/,"");
		print "<li>" $0  ;
		text = "";
		next;
	}
	/^[0-9]./ {
		if (env == "none") {
			env = "ol";
			print "<ol>";
		}
		print "<li>" substr($0, 3) "</li>";
		next;
	}
	/^[ \t]*$/ {
		if (env != "none") {
			if (text)
				print text;
			text = "";
			print "</" env ">\n";
			env = "none"; 
	} }
	/^[ \t]*$/ {
		paraOrPre()
		next;
	}
	// {
		text = (text ? text "\n" : "" ) $0;
	}
	END {
	        if (env != "none") {
	                if (text)
	                        print text;
	                text = "";
	                print "</" env ">\n";
	                env = "none";
	        }
			paraOrPre()
	        text = "";
	}
	function paraOrPre() {
		if (text) {
			if (text ~ /^[ \t]/)
				print "<pre>" text "</pre>\n"
			else 
				print "<p>" text "</p>\n"
		}
		text = "";
	}
' Toc=$TimLog/$Stem.toc
}
############################################
#### start up
config
while getopts "a:c:C:r:R:m:M:is:S:l:t:T:vxo:w:DKh" opt; do opt $opt "$OPTARG"; done
shift $((OPTIND - 1))
