#!/usr/local/bin/tclsh8.1
set ctr [lindex $argv 0]
set interval [lindex $argv 1]
eval "exec echo interval: $interval > out.rate"
eval "exec ./ns increase.tcl $interval >> out.rate"
eval "exec awk -f awk/increase.awk out.rate > graphs/s$ctr.rate"
eval "exec sed \"s/s0/s$ctr/g\" < graphs/s0.packetrate.mf > graphs/s$ctr.packetrate.mf"

# out.rate:
# interval: 100
# time: 23.55 rate: 8437.52

# graphs/s$ctr.rate
# 23.55 8437.52

